"""Read/write hyprland-gui.conf — hyprmod's managed config file."""

from pathlib import Path

from hyprland_config import Assignment, Keyword, atomic_write, is_bind_keyword
from hyprland_config import load as load_document

HYPRMOD_DIR = Path.home() / ".config" / "hypr" / "hyprmod"
GUI_CONF = Path.home() / ".config" / "hypr" / "hyprland-gui.conf"

_NON_BIND_SPECIAL = frozenset(("monitor", "animation", "bezier", "unbind"))


class _BindKeysSentinel:
    """Sentinel type for ``collect_section()`` to match all bind-variant keywords."""

    __slots__ = ()

    def __repr__(self) -> str:
        return "BIND_KEYS"


BIND_KEYS = _BindKeysSentinel()


def _is_special_keyword(name: str) -> bool:
    """Check if a keyword name is a special key (bind variants, monitor, animation, etc.)."""
    return name in _NON_BIND_SPECIAL or is_bind_keyword(name)


def parse_conf(path: Path) -> dict[str, str]:
    """Parse all key=value pairs from a .conf file (comments and blanks skipped)."""
    if not path.exists():
        return {}
    doc = load_document(path, follow_sources=False)
    return {line.full_key: line.value for line in doc.lines if isinstance(line, Assignment)}


def read_all_sections(
    path: Path | None = None,
) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Single-pass parse of a config file.

    Returns (options, sections) where:
    - options: key -> value for regular option lines
    - sections: section_key -> [raw lines] for special keys (bind, monitor, etc.)
    """
    path = path or GUI_CONF
    if not path.exists():
        return {}, {}
    doc = load_document(path, follow_sources=False)
    options: dict[str, str] = {}
    sections: dict[str, list[str]] = {}
    for line in doc.lines:
        if isinstance(line, Assignment):
            options[line.full_key] = line.value
        elif isinstance(line, Keyword) and _is_special_keyword(line.key):
            raw = line.raw.strip()
            sections.setdefault(line.key, []).append(raw)
    return options, sections


def collect_section(
    sections: dict[str, list[str]],
    *keys: str | _BindKeysSentinel,
) -> list[str]:
    """Extract lines from a pre-parsed sections dict.

    Each *key* can be a single string or the sentinel ``BIND_KEYS``
    which matches all bind-variant keywords present in *sections*.
    """
    result = []
    for key in keys:
        if isinstance(key, _BindKeysSentinel):
            for k in sections:
                if is_bind_keyword(k):
                    result.extend(sections[k])
        else:
            result.extend(sections.get(key, []))
    return result


def remove_key(key: str) -> None:
    """Remove a single key from GUI_CONF, preserving everything else."""
    if not GUI_CONF.exists():
        return
    doc = load_document(GUI_CONF, follow_sources=False)
    doc.remove(key)
    doc.save()


def remove_animation(name: str) -> None:
    """Remove a single animation line from GUI_CONF by animation name."""
    if not GUI_CONF.exists():
        return
    doc = load_document(GUI_CONF, follow_sources=False)
    doc.remove_where("animation", lambda v: v.split(",")[0].strip() == name)
    doc.save()


def _append_section(lines: list[str], header: str, section_lines: list[str]) -> None:
    """Append a labeled section of config lines, normalizing line endings."""
    lines.append(f"\n# {header}\n")
    for line in section_lines:
        lines.append(line if line.endswith("\n") else line + "\n")


def write_all(
    values: dict[str, str],
    bind_lines: list[str] | None = None,
    monitor_lines: list[str] | None = None,
    animation_lines: list[str] | None = None,
    bezier_lines: list[str] | None = None,
) -> None:
    """Write all values and special lines to GUI_CONF."""
    lines: list[str] = ["# Generated by HyprMod\n\n"]

    for k, v in sorted(values.items()):
        lines.append(f"{k} = {v}\n")

    if bezier_lines:
        _append_section(lines, "Bezier curves", bezier_lines)
    if animation_lines:
        _append_section(lines, "Animations", animation_lines)
    if monitor_lines:
        _append_section(lines, "Monitors", monitor_lines)
    if bind_lines:
        _append_section(lines, "Keybinds", bind_lines)

    atomic_write(GUI_CONF, "".join(lines))
